# 新建docker-compose.yml
version: "3.8"
services:
  webhook2feishu:
    image: ghcr.io/always1ov/webhook2feishu:latest
    ports:
      - "38080:8080"
    environment:
      - FEISHU_WEBHOOK_URL=你的飞书地址
    restart: always
